apiVersion: v1
kind: Service
metadata:
  name: fintech-service
  labels:
    app: fintech
spec:
  type: LoadBalancer
  selector:
    app: fintech
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
